version: 2.1

jobs:
  noop:
    docker:
      - image: cimg/base:2024.01
    steps:
      - run: echo noop

workflows:
  many-jobs:
    jobs:
      - noop:
          name: noop-1
      - noop:
          name: noop-2
      - noop:
          name: noop-3
      - noop:
          name: noop-4
      - noop:
          name: noop-5
      - noop:
          name: noop-6
      - noop:
          name: noop-7
      - noop:
          name: noop-8
      - noop:
          name: noop-9
      - noop:
          name: noop-10
      - noop:
          name: noop-11
      - noop:
          name: noop-12
      - noop:
          name: noop-13
      - noop:
          name: noop-14
      - noop:
          name: noop-15
      - noop:
          name: noop-16
      - noop:
          name: noop-17
      - noop:
          name: noop-18
      - noop:
          name: noop-19
      - noop:
          name: noop-20
      - noop:
          name: noop-21
      - noop:
          name: noop-22
      - noop:
          name: noop-23
      - noop:
          name: noop-24
      - noop:
          name: noop-25
      - noop:
          name: noop-26
      - noop:
          name: noop-27
      - noop:
          name: noop-28
      - noop:
          name: noop-29
      - noop:
          name: noop-30
      - noop:
          name: noop-31
      - noop:
          name: noop-32
      - noop:
          name: noop-33
      - noop:
          name: noop-34
      - noop:
          name: noop-35
      - noop:
          name: noop-36
      - noop:
          name: noop-37
      - noop:
          name: noop-38
      - noop:
          name: noop-39
      - noop:
          name: noop-40
      - noop:
          name: noop-41
      - noop:
          name: noop-42
      - noop:
          name: noop-43
      - noop:
          name: noop-44
      - noop:
          name: noop-45
      - noop:
          name: noop-46
      - noop:
          name: noop-47
      - noop:
          name: noop-48
      - noop:
          name: noop-49
      - noop:
          name: noop-50
